import streamlit as st
import os
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

st.title("⚙️ Settings & Configuration")
st.markdown("---")

class SettingsManager:
    """Manage configuration settings."""
    
    @staticmethod
    def save_settings(settings):
        """Save settings to .env file."""
        try:
            env_path = ".env"
            existing_settings = {}
            
            if os.path.exists(env_path):
                with open(env_path, 'r') as f:
                    for line in f:
                        if '=' in line and not line.strip().startswith('#'):
                            key, value = line.strip().split('=', 1)
                            existing_settings[key] = value
            
            existing_settings.update(settings)
            
            with open(env_path, 'w') as f:
                f.write("# Forex Trading Bot Configuration\n")
                f.write("# Auto-generated by Settings page\n\n")
                for key, value in existing_settings.items():
                    f.write(f"{key}={value}\n")
            
            return True
        except Exception as e:
            st.error(f"Error saving settings: {e}")
            return False

# Create tabs for different settings categories
tab1, tab2, tab3, tab4, tab5 = st.tabs(["📊 Basic", "🎯 Strategy", "🔗 MT5", "💰 Risk", "🔄 Advanced"])

with tab1:
    st.header("Basic Trading Settings")
    col1, col2, col3 = st.columns(3)
    
    with col1:
        symbol = st.selectbox("Default Symbol",
                             ["EURUSD", "GBPUSD", "USDJPY", "AUDUSD", "USDCAD"],
                             index=["EURUSD", "GBPUSD", "USDJPY", "AUDUSD", "USDCAD"].index(os.getenv("SYMBOL", "EURUSD")))
    
    with col2:
        timeframe = st.selectbox("Default Timeframe",
                                ["M1", "M5", "M15", "H1", "D1"],
                                index=["M1", "M5", "M15", "H1", "D1"].index(os.getenv("TIMEFRAME", "M5")))
    
    with col3:
        lot_size = st.slider("Default Lot Size", 0.01, 1.0, float(os.getenv("LOT", "0.1")), 0.01)

with tab2:
    st.header("🎯 Strategy Parameters")
    st.info("💡 Adjust these to optimize your trading signals")
    
    col1, col2 = st.columns(2)
    
    with col1:
        st.subheader("📈 Moving Averages")
        sma_short = st.slider("Short SMA Period", 10, 100, int(os.getenv("SMA_SHORT", "50")), 5,
                             help="Faster moving average for trend detection")
        sma_long = st.slider("Long SMA Period", 100, 300, int(os.getenv("SMA_LONG", "200")), 10,
                            help="Slower moving average for long-term trend")
    
    with col2:
        st.subheader("📊 RSI Settings")
        rsi_period = st.slider("RSI Period", 5, 30, int(os.getenv("RSI_PERIOD", "14")), 1)
        rsi_oversold = st.slider("RSI Oversold Level", 10, 40, int(os.getenv("RSI_OVERSOLD", "30")), 1,
                                help="Values below this = potential buy signal")
        rsi_overbought = st.slider("RSI Overbought Level", 60, 90, int(os.getenv("RSI_OVERBOUGHT", "70")), 1,
                                  help="Values above this = potential sell signal")
    
    col1, col2 = st.columns(2)
    
    with col1:
        st.subheader("🎵 MACD Settings")
        macd_fast = st.slider("MACD Fast Period", 5, 20, int(os.getenv("MACD_FAST", "12")), 1)
        macd_slow = st.slider("MACD Slow Period", 20, 50, int(os.getenv("MACD_SLOW", "26")), 1)
        macd_signal = st.slider("MACD Signal Period", 5, 15, int(os.getenv("MACD_SIGNAL", "9")), 1)
    
    with col2:
        st.subheader("📊 Bollinger Bands")
        bb_period = st.slider("BB Period", 10, 40, int(os.getenv("BB_PERIOD", "20")), 1)
        bb_std = st.slider("BB Standard Deviation", 1.0, 3.0, float(os.getenv("BB_STD_DEV", "2.0")), 0.1)
    
    col1, col2 = st.columns(2)
    
    with col1:
        st.subheader("🎯 Signal Confirmation")
        signal_conf = st.slider("Required Signal Confirmations", 1, 4, int(os.getenv("SIGNAL_CONFIRMATION_COUNT", "2")), 1,
                               help="How many indicators must align for a trade signal")
    
    with col2:
        st.info(f"ℹ️ Your strategy requires **{signal_conf} signal(s)** to align before trading")

with tab3:
    st.header("🔗 MetaTrader 5 Connection")
    st.warning("⚠️ **Security:** Credentials are stored locally. Never share your .env file!")
    
    col1, col2 = st.columns(2)
    
    with col1:
        mt5_login = st.text_input("MT5 Account Number",
                                 value=os.getenv("MT5_LOGIN", ""),
                                 type="password",
                                 help="Your MetaTrader 5 login number")
        
        mt5_password = st.text_input("MT5 Password",
                                    value=os.getenv("MT5_PASSWORD", ""),
                                    type="password",
                                    help="Your MetaTrader 5 password")
    
    with col2:
        mt5_server = st.text_input("MT5 Server",
                                  value=os.getenv("MT5_SERVER", ""),
                                  help="e.g., MetaQuotes-Demo or your broker's server")
        
        st.info("💡 Find your server name in MT5: Tools → Options → Account")

with tab4:
    st.header("💰 Risk Management")
    st.info("🛡️ Protect your account with proper risk controls")
    
    col1, col2 = st.columns(2)
    
    with col1:
        st.subheader("📍 Order Levels")
        stop_loss = st.slider("Stop Loss (Pips)", 10, 200, int(os.getenv("STOP_LOSS_PIPS", "50")), 5,
                             help="Distance to stop loss from entry")
        take_profit = st.slider("Take Profit (Pips)", 10, 500, int(os.getenv("TAKE_PROFIT_PIPS", "100")), 10,
                               help="Distance to take profit from entry")
    
    with col2:
        st.subheader("📊 Account Protection")
        risk_percentage = st.slider("Risk per Trade (%)", 0.1, 5.0, 
                                   float(os.getenv("RISK_PERCENTAGE", "0.02")) * 100, 0.1,
                                   help="% of account risked per trade") / 100
        max_drawdown = st.slider("Max Drawdown (%)", 1, 20, 
                                int(float(os.getenv("MAX_DRAWDOWN_PERCENTAGE", "0.1")) * 100), 1,
                                help="Maximum account decline before stopping") / 100

with tab5:
    st.header("🔄 Advanced Settings")
    
    col1, col2 = st.columns(2)
    
    with col1:
        st.subheader("📊 Data Settings")
        data_points = st.slider("Data Points to Fetch", 1000, 10000, 5000, 500,
                               help="More historical data improves accuracy but slows loading")
    
    with col2:
        st.subheader("🤖 ML Settings")
        ml_enabled = st.checkbox("Enable Machine Learning Signals", value=True,
                                help="Combine technical analysis with ML predictions")

st.markdown("---")
st.header("💾 Save Configuration")

all_settings = {
    'SYMBOL': symbol,
    'LOT': str(lot_size),
    'TIMEFRAME': timeframe,
    'STOP_LOSS_PIPS': str(stop_loss),
    'TAKE_PROFIT_PIPS': str(take_profit),
    'RISK_PERCENTAGE': str(risk_percentage),
    'MAX_DRAWDOWN_PERCENTAGE': str(max_drawdown),
    'MT5_LOGIN': mt5_login,
    'MT5_PASSWORD': mt5_password,
    'MT5_SERVER': mt5_server,
    'RSI_PERIOD': str(rsi_period),
    'RSI_OVERSOLD': str(rsi_oversold),
    'RSI_OVERBOUGHT': str(rsi_overbought),
    'BB_PERIOD': str(bb_period),
    'BB_STD_DEV': str(bb_std),
    'MACD_FAST': str(macd_fast),
    'MACD_SLOW': str(macd_slow),
    'MACD_SIGNAL': str(macd_signal),
    'SMA_SHORT': str(sma_short),
    'SMA_LONG': str(sma_long),
    'SIGNAL_CONFIRMATION_COUNT': str(signal_conf)
}

col1, col2, col3 = st.columns(3)

with col1:
    if st.button("💾 Save Settings", type="primary", use_container_width=True):
        if SettingsManager.save_settings(all_settings):
            st.success("✅ Configuration saved successfully!")
            st.balloons()

with col2:
    if st.button("📋 Show Current Config", use_container_width=True):
        with st.expander("Current Configuration", expanded=True):
            import pandas as pd
            config_df = pd.DataFrame(list(all_settings.items()), columns=['Key', 'Value'])
            st.dataframe(config_df, use_container_width=True)

with col3:
    if st.button("🔄 Reload Settings", use_container_width=True):
        st.rerun()

def reset_to_defaults():
    """Reset settings to defaults."""
    default_settings = {
        'SYMBOL': 'EURUSD',
        'LOT': '0.1',
        'STOP_LOSS_PIPS': '50',
        'TAKE_PROFIT_PIPS': '100',
        'RISK_PERCENTAGE': '0.02',
        'MAX_DRAWDOWN_PERCENTAGE': '0.1',
        'TIMEFRAME': 'M5'
    }

    # Keep MT5 credentials if they exist
    if os.path.exists('.env'):
        load_dotenv()
        if os.getenv('MT5_LOGIN'):
            default_settings['MT5_LOGIN'] = os.getenv('MT5_LOGIN')
        if os.getenv('MT5_PASSWORD'):
            default_settings['MT5_PASSWORD'] = os.getenv('MT5_PASSWORD')
        if os.getenv('MT5_SERVER'):
            default_settings['MT5_SERVER'] = os.getenv('MT5_SERVER')

    save_settings(default_settings)